[Task] Add html structure design
st-thiennguyen/FE-Internship-2023_Thien-nguyen-S_FE-Exercise_ pull request #2
Opened 2023-08-04 09:07 UTC by st-thiennguyen

### Description
- Add html structure 
- Learn how to use tags element

### Checklist
- [x] Website run correctly
- [x] The code has been tested in the local environment.
- [x] No convention errors

2023-08-04 16:11 UTC, st-ngabui requested changes
Chị tóm lại những nội dung chính e cần sửa (một số comment bị ẩn nên e nhớ show ra để xem hết nha):
- Sử dụng vị trí của div.container hợp lí
- Đặt tên class phù hợp hơn
- Sử dụng h1 cho logo
- Sử dụng ul, li cho các danh sách
- Xem xét xem item đó có move tới page khác được không để sử dụng thẻ a

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +    <title>Home</title>
Title của trang web nên đặt nêu rõ được trang web đó là gì e nha

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +    <div class="container">
container nó ko nên bọc ngoài cùng thế này, vì có 1 số section ko dùng đến nó. Để nó vào trong những section cần thiết

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +          <img src="" alt="Logo E shop" class="logo-header" />
Sử dụng h1 cho logo để tối ưu hoá SEO.
Ngoài ra logo thường link đến trang home => sử dụng thẻ a
Chữ E-shop nằm trong image của logo đó e, chứ ko phải text để define riêng

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <div class="header-right">
list icon này sử dụng ul, li

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <section class="banner">
Với section mình nên đặt tên class như sau:

- class đầu là section
- class thứ 2 là section-{name_section}
=> class="section section-banner"

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <h1 class="banner-title-txt">Sale of the summer collection</h1>
Vì h1 mình để cho logo nên sẽ đổi lại thành h2 nha

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <img src="" alt="Banner image of website" />
image của banner sẽ được set trong background-img => ko cần dùng thẻ img ở đây

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +          <div class="banner-title">
Vì thẻ div này chứa cả title và action bên dưới => tên class chưa hợp lý, nên đặt là banner-content

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <a href="#" class="banner-title-btn">
icon và text trong thẻ a này nó ko phải là dạng button => nên đặt class là `banner-action` thay vì `banner-title-btn`

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <div class="statistic-title">
đặt class `statistic-title` cho nội dung của title + description là chưa hợp lý. 
Mình có thể đặt là statistic-content

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +                <span class="statistic-title-text">Free Shipping</span>
title của item này nên đặt thẻ heading (h4). Và class là `statistic-title`

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +                <p class="statistic-title-label">On purchases over $199</p>
Sửa class cho hợp lý hơn statistic-title-label => statistic-description

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <section class="slider">
chị nghĩ cái tên slider chưa hợp lý lắm, vì nhìn vào design chị ko thấy nó là slide. Chị suggest tên class là `section section-categories`.
Và class của ul > li phía dưới nên là categories > category

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <h5 class="slider-top-title">New arrivalsare now in!</h5>
title này nên để thẻ h4

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <button class="primary-btn">Show collection</button>
Click vào đây sẽ move tới trang khác => sử dụng thẻ a

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +          <div class="product-bestseller">
Cái này là 1 section e nha

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <h4 class="bestseller-txt">Selected just for you</h4>
Sử dụng thẻ h3 cho title của section và những section sau.
Thẻ h3 này nếu để ý nó là title của section và được sử dụng lại ở những phần sau nữa => có thể đặt tên section-title để apply chung cho những title section khác

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <li class="product-item">
Khi click product sẽ move tới trang detail => sử dụng thẻ a

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +                  <p class="product-item-name">T-Shirt Summer Vibes</p>
Sử dụng thẻ h4 cho tên sản phẩm

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +                  <div class="product-item-price">
nên có thêm class để css cho mục price của những sản phẩm được giảm giá khác với không được giảm giá

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <li class="service-item">
Vì item thứ 2 trong section có title và icon màu khác => khả năng cao click đươcj qua trang khác => dùng thêm thẻ a

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <li class="service-item">
Item thứ 2 có css hơi khác những cái kia => add thêm class "service-active" để sau này css cho nó

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <section class="recommend">
sửa giống cmt của mục Selected just for you

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <button class="primary-btn yellow-btn">SUBSCRIBE</button>
tên class nó vẻ hơi ngược nên đảo thành btn-primary, btn-yellow

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <div class="footer-contact">
mục này là 1 section, ko phải footer nha e

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +        <div class="footer-about">
Thêm thẻ footer cho mục này. Chị nghĩ có thể đặt class này thành footer-top

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +            <ul class="footer-about-us-social">
nên đặt class cho ul này là social-list

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <li class="social-item">
Thêm thẻ a vào để link tới trang tương ứng

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +              <h5 class="service-txt">Shopping online</h5>
title dưới footer chị nghĩ ko cần phải dùng thẻ heading

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +                <li class="service-item">Order Status</li>
Mấy item này bỏ thẻ a vào nha e

2023-08-04 16:11 UTC, st-ngabui commented on index.html
> +          <div class="footer-about-service">
Sử dụng ul, li cho các cột này nha

2023-08-06 02:16 UTC, st-ngabui requested changes
Check cmts

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +      <div class="header-container">
container sẽ dùng chung nên e đặt class là "container" thôi.
Em check và sửa thêm ở những chỗ khác nữa

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +              <img src="" alt="Logo E shop" class="logo-header" />
class nên là logo-img sẽ hợp lý hơn e nha

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +            <li class="extend-item">
class chỗ này sao lại là "extend-item", nên là icon-item nha

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +              <a href=""><i class="fa-solid fa-magnifying-glass"></i></a>
e đặt tên class cho cả thẻ a nữa nha, check lại những chỗ khác nữa

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +        <ul class="banner-statitics">
Nên thêm class `statitic-list` vào nữa

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +              <input type="email" placeholder="Enter your email" required />
thêm class vào nha e

2023-08-06 02:16 UTC, st-ngabui commented on index.html
> +          </div>
1 cột này là 1 li. Mình sẽ sử dung ul, li cho danh sách các cột thông tin của shop và trong li lại chứa ul>li cho danh sách các link.
Mục này chị nghĩ dùng infor-shop nó sẽ hợp hơn là dùng footer-menu.

2023-08-06 04:39 UTC, st-thiennguyen commented on index.html
> +      <div class="header-container">
mình có nên đặt class là container + container-{mục cần bọc bởi container} không chị nhỉ ?, do em thấy một số layout bên trong từng phần khác nhau ạ

2023-08-06 09:03 UTC, st-ngabui commented on index.html
> +      <div class="header-container">
Sử dụng container để cho nội dung bên trong nó ko vượt quá max-width mình mong muốn. Và max-width này là thông số dùng chung trên nhiều section.
Những section mà ko có max-width giống với container thì mình ko cần đặt tên class container luôn.

2023-08-06 09:18 UTC, st-ngabui commented
@st-thiennguyen 
Chị có 1 số góp ý cho mục ảnh của em:
- Em move thư mục icons vào trong thư mục images luôn
- Tên ảnh:
  - Đã là ảnh rồi thì e không cần thêm chữ image nữa
  - Với icon thì mình có thể đặt theo dạng ic-{name-icon}
  - Không để dấu cách trong tên ảnh

2023-08-07 12:46 UTC, st-ngabui approved these changes

2023-08-07 23:28 UTC, merged