[Task] Convert css to scss
st-thiennguyen/FE-Internship-2023_Thien-nguyen-S_FE-Exercise_ pull request #5
Opened 2023-08-10 10:03 UTC by st-thiennguyen

### Description
- Convert css file to scss

### Checkline
- [ ] App run correctly
- [ ] The code has been tested in the local environment.
- [ ] No convention errors

2023-08-11 07:24 UTC, st-ngabui requested changes

2023-08-11 07:24 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/base/_variable.scss
> +  primaryColor: #fbb03b,
Vì có tên biến $color rồi, nên những mục trong này e chỉ ghi tên ko cần kèm theo Color (primaryColor => primary)

2023-08-11 07:24 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/layout/_grid.scss
> +  margin: 0 auto;
thêm width: 100%

2023-08-11 07:24 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/modules/_button.scss
> +  border-radius: 33.33px;
Giá trị px ko nên dùng thập phân e nghe

2023-08-11 07:24 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/pages/_home.scss
> +  }
Chị có 1 lưu ý là category-item e đang đặt tên cho thẻ li, trong li nên có 1 thẻ div có tên category (nó là 1 đối tương). Trong category sẽ có category-img, category-content chứ ko nên đặt category-item-img, category-item-content.
```
.category {
   &-img {
   }
   &-content {
   }
}
```
Em để ý check lại chỗ này cho những chỗ tương tự

2023-08-11 14:14 UTC, st-thiennguyen commented on Exercise-html-css/stylesheet/scss/pages/_home.scss
> +  }
- cái này em hiểu nhầm code của chị nên em sửa sai rồi, chị đợi chút em commit lại ạ ^^

2023-08-12 10:09 UTC, st-ngabui requested changes
check cmts

2023-08-12 10:09 UTC, st-ngabui commented on Exercise-html-css/index.html
> +            <li class="category col col-6 col-sm-12">
Nên đặt class cho thẻ li là category-item

2023-08-12 10:09 UTC, st-ngabui commented on Exercise-html-css/index.html
> +              <div class="category-img">
Class chỗ này là category chứ e nhở, sao category-img lại chứa cả text nữa e

2023-08-12 10:09 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/modules/_button.scss
> +
btn-subcribe dùng ở phần subcribe thôi thì nên bỏ vào _home.scss e nha. Mà 
```
border: none;
outline: none;
```
nó nên là thuộc tính chung của .btn chứ e nhỉ

2023-08-12 10:09 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/pages/_home.scss
> +        }
Em có thể đưa .statistic ra ngoài , ko cần lồng trong banner nha, tránh lồng nhau nhiều quá

2023-08-12 10:09 UTC, st-ngabui commented on Exercise-html-css/stylesheet/scss/pages/_home.scss
> +  }
3 class này có chung font-size, e có thể CSS font-size chung cho .product-price

2023-08-13 06:16 UTC, st-thiennguyen commented on Exercise-html-css/index.html
> +              <div class="category-img">
ui, em nhầm , cảm ơn chị đã nhắc ạ ^^

2023-08-15 07:40 UTC, st-ngabui approved these changes

2023-08-15 07:40 UTC, merged